apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana
spec:
  rules:
  - host: kibana.185.145.251.54.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: 5601
